# Python tutorial

In [1]:
# Procedural code
def simple_interest(p, r, t):
    return(p*r*t/100)

def compound_interest(p, r, t):
    return(p*pow(1+(r/100), t))

principle = 100
interest = 0
time = 10

compound_interest(principle, 7, 10)

196.71513572895665

In [95]:
# OOPs code

class loan():
    n = 20 # class variable shared by all instances
    def __init__(self): #initialisation
        self.principle = 100
        self.interest = 0
        self.time = 10
        self.n = 20 # instance variable unique to each instance
    def compound_interest(self, r, t):
        return(self.principle*pow(1+(r/100), t))
    def simple_interest(self,p, r, t):
        return(p*r*t/100)
    
a = loan()
b = loan()
# a = dict()
# a = list()
print(a.compound_interest(7, 10))
print(a.simple_interest(10, 7, 10))

196.71513572895665
7.0


In [ ]:
a = [1 ,2, 3]

## Classes

A class is a kind of data type, just like a string, integer or list. When we create an object of that data type, we call it an instance of a class.

Each class has a separate environment (no collision on function names)

In Python, everything is an object – everything is an instance of some class. 

In [2]:
'''
int a = 10;
string s;

class Node()
{
    int a;
    Node* next = NULL;
    public:
    void display()
    {
        cout<<a;
    }
}

Node a = new Node;
a.display();
'''

'\nint a = 10;\nstring s;\n\nclass Node()\n{\n    int a;\n    Node* next = NULL;\n    public:\n    void display()\n    {\n        cout<<a;\n    }\n}\n\nNode a = new Node;\na.display();\n'

In [3]:
a = int(10)
print(type(a))

c = list()
c.append(10)
print(type(c))

<class 'int'>
<class 'list'>


In [34]:
class Coordinate():
    abc = 10    
    def __init__(self, x, y): # different instances will have diff values
        self.x = x
        self.y = y
        
    def distance(self, other):
        x_diff_sq = (self.x-other.x) ** 2
        y_diff_sq = (self.y-other.y) ** 2
        return (x_diff_sq + y_diff_sq) ** 0.5
    
    def __str__(self):
        return("("+str(self.x)+", "+str(self.y)+")")



Variable set outside __init__ belong to the class. They're shared by all instances.

Variables created inside __init__ (and all other method functions) and prefaced with self. belong to the object instance.


In [36]:
c = Coordinate(3, 4)
print(c)
print(c.x, c.y)

(3, 4)
3 4


In [37]:
d = Coordinate(5, 12)
print(d)
print(d.x, d.y)

(5, 12)
5 12


In [23]:
# The internal working, DO NOT CODE THIS WAY
# c = Coordinate(5, 12)
Coordinate.__init__(c, 5, 12) # the reason for self
# print(c)

In [24]:
zero = Coordinate(0,0)

In [25]:
print(c.distance(zero)) #Coordinate.distance(c,zero)
print(zero.distance(c))

13.0
13.0


In [26]:
# The internal working, DO NOT CODE THIS WAY.
# c.distance(zero)
Coordinate.distance(c, zero)

13.0

In [38]:
a = [1, 2, 3, 4]
print(a)

[1, 2, 3, 4]


In [44]:
# Everything is an object in Python

sample = list([1, 2])  # c = Coordinate(3, 4)
sample2 = [1, 2, 3]   # zero = Coordinate(0,0)
sample.append(sample2)  # c.distance(zero)

In [45]:
print(sample)

[1, 2, [1, 2, 3]]


In [42]:
print(isinstance(c, Coordinate))

True


In [51]:
class ComplexNumber():
    def __init__(self, x, y):
        self.x = x
        self.y = y
    def add(self, other):
        self.x += other.x
        self.y += other.y
    
    def sub(self, other):
        self.x -= other.x
        self.y -= other.y
    
    def __str__(self):
        return(str(self.x)+"i + "+str(self.y)+"j")
c1 = ComplexNumber(2, 5)
c2 = ComplexNumber(3, 4)
c1.add(c2)
print(c1)

5i + 9j


## Numpy


NumPy provides
* extension package to Python for multi-dimensional arrays
* closer to hardware (efficiency)
* designed for scientific computation (convenience)
* Also known as array oriented computing

In [47]:
'''

#include <cmath> 

using namespace std; 

int main()
{ int a;
cout<<"Hello";
cin>>a;
}


'''

'\n\n#include <cmath> \n\nusing namespace std; \n\nint main()\n{ int a;\ncout<<"Hello";\ncin>>a;\n}\n\n\n'

In [48]:
# from numpy import *
# __version__

In [52]:
import numpy as np
np.__version__

'1.21.5'

In [53]:
# Mention tab completion

In [54]:
np.__version__

'1.21.5'

In [57]:
?np.__version__

In [61]:
np.lookfor("unique elements")

Search results for 'unique elements'
------------------------------------
numpy.unique
    Find the unique elements of an array.
numpy.ma.unique
    Finds the unique elements of an array.
numpy.ma.setxor1d
    Set exclusive-or of 1-D arrays with unique elements.
numpy.ma.setdiff1d
    Set difference of 1D arrays with unique elements.
numpy.ma.intersect1d
    Returns the unique elements common to both arrays.
numpy.isin
    Calculates `element in test_elements`, broadcasting over `element` only.
numpy.repeat
    Repeat elements of an array.
numpy.intersect1d
    Find the intersection of two arrays.
numpy.bincount
    Count number of occurrences of each value in array of non-negative ints.
numpy.array2string
    Return a string representation of an array.
numpy.set_printoptions
    Set printing options.
numpy.core._multiarray_umath.bincount
    Count number of occurrences of each value in array of non-negative ints.

In [62]:
test = np.array([1,2,3,4,5])
test2 = np.array([[1,2],[3,4]])

print(type(test), type(test2), test.shape, test2.shape)

<class 'numpy.ndarray'> <class 'numpy.ndarray'> (5,) (2, 2)


In [66]:
print(test.ndim)

1


In [69]:
print(test6)

[10]


In [70]:
test6 = list()
test6.append(10)
print(test6)
test6 = np.array(test6)
print(type(test6))
print(test6.dtype)

[10]
<class 'numpy.ndarray'>
int64


In [71]:
abc = np.array([1, 2, 3, 4], dtype='float32')
abc[0] = 100
print(abc)

[100.   2.   3.   4.]


In [84]:
sample = [1, 2, 3] + [4, 5, 6]

In [85]:
sample2 = sample[:]

In [86]:
print(sample)

[1, 2, 3, 4, 5, 6]


In [87]:
sample = np.array(sample)

In [89]:
print(sample + sample, sample2 + sample2)

[ 2  4  6  8 10 12] [1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]


In [110]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [122]:
len(np.ones((3, 5), dtype=float))

3

In [ ]:
#?, ??, np.lookfor, shift+tab, tab completion

In [123]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [124]:
np.arange(0, 20, 2) #start, stop, step

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [133]:
np.linspace(1, 5, 11) #start, stop, no. points

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [180]:
np.random.seed(12)
np.random.rand(4)

array([0.15416284, 0.7400497 , 0.26331502, 0.53373939])

In [207]:
print(np.random.rand(4)) #uniform in [0,1]
print(np.random.randint(10, 20, size=(2,2)))

[0.37945046 0.12939229 0.60332683 0.07200462]
[[14 13]
 [12 18]]


In [195]:
test = [1, 2, 3, 4, 5]
print(test * 2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [196]:
print(test*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [197]:
print(test + 4*test)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [198]:
test3 = np.array([1,2,3,4,5], dtype=float)

In [200]:
test3 + 4*test3

array([ 5., 10., 15., 20., 25.])

In [214]:
test3 = np.array([1,2,3,4,5], dtype=float)
print(test3)

[1. 2. 3. 4. 5.]


In [215]:
print("test3 =", test3)

print('test3 dtype =', test3.dtype)
# a = int(input())
test3 = test3.astype(np.uint8)

print('test3 dtype =', test3.dtype)

test3 = [1. 2. 3. 4. 5.]
test3 dtype = float64
test3 dtype = uint8


In [42]:
print('test3', test3)
# array[start:stop:skip]
print('test3[::2]', test3[::2])
print('test3[1::2]', test3[1::2])

test3 [1. 2. 3. 4. 5.]
test3[::2] [1. 3. 5.]
test3[1::2] [2. 4.]


In [43]:
list_a = [[1,2], [3,4]]
print(list_a[0][0])
# print(list_a[0,0])

1


In [44]:
print('test2', test2, sep="\n")
print('test2[1,1]', test2[1,1])
print('test2[1,:]', test2[1,:])
print('test2[:,1]', test2[:,1])

test2
[[1 2]
 [3 4]]
test2[1,1] 4
test2[1,:] [3 4]
test2[:,1] [2 4]


In [45]:
row_indices = [1, 2, 3]
print(test3[row_indices])

[2. 3. 4.]


In [73]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])

print(A)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


In [47]:
row_indices = [1, 1, 2]
col_indices = [0, 1, 2]
A[row_indices, col_indices]

array([10, 11, 22])

In [48]:
x = np.ones((3, 5), dtype=float)

print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)

x ndim:  2
x shape: (3, 5)
x size:  15


In [49]:
x.dtype

dtype('float64')

In [50]:
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [51]:
y = x #changes to y is reflected in x

y[0, :] = 0

print(x)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [52]:
np.may_share_memory(y,x)

True

In [53]:
x = np.ones((3, 5), dtype=float)

y = x.copy()

y[0, :] = 0

print(x)
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [54]:
np.may_share_memory(y,x)

False

In [55]:
x.reshape((5,3))
# x = x.reshape((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [57]:
x = x.reshape((5,3))

print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [58]:
#element-wise operation
a = np.array([1, 2, 3, 4])
print(a+1)

[2 3 4 5]


In [59]:
print(2*a)

[2 4 6 8]


In [60]:
c = np.ones((3, 3))
print(c * c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [61]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
print(a == b)

[False  True False  True]


In [62]:
np.array_equal(a, b)

False

In [63]:
#Basic reductions
x = np.array([1, 2, 3, 4])
print(x.sum())

10


In [64]:
x = np.array([[1, 1], [2, 2]])
print(x.sum(axis=0))

[3 3]


In [65]:
print(x.sum(axis=1))

[2 4]


In [74]:
# Speed test - bear in mind that list comprehensions are vectorised

def custom_dot(A, B):
  
  C = [[0 for i in range(len(B[0]))] for j in range(len(A))]
  
  for i in range(len(A)):
    for j in range(len(B[0])):
      C[i][j] = sum(A[i,:] * B[:,j])
  
  return C
    
%timeit using_numpy = np.dot(A,A)
%timeit raw_python = custom_dot(A,A)

910 ns ± 2.92 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
36.2 µs ± 487 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [75]:
big_array = np.random.rand(100000)
%timeit sum(big_array)
%timeit np.sum(big_array)

4.1 ms ± 15.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
23.4 µs ± 179 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [76]:
%timeit min(big_array)
%timeit np.min(big_array)

3.13 ms ± 38.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
27.4 µs ± 188 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [69]:
# Boolean masks
a = np.random.randint(0, 21, 15)
print(a)

[14 17  6 13 13  4  2  3  4 11  4  1  9  3  0]


In [70]:
(a % 3 == 0)

array([False, False,  True, False, False, False, False,  True, False,
       False, False, False,  True,  True,  True])

In [71]:
print(a[(a % 3 == 0)])

[6 3 9 3 0]


In [72]:
a[(a % 3 == 0)] = -1
print(a)

[14 17 -1 13 13  4  2 -1  4 11  4  1 -1 -1 -1]


In [73]:
M = np.random.random((3, 4))
print(M)

M.min(axis=0)

[[0.90629332 0.16592425 0.46272352 0.54188595]
 [0.33680638 0.68037286 0.72231083 0.44674389]
 [0.40194649 0.38341765 0.38890679 0.51486002]]


array([0.33680638, 0.16592425, 0.38890679, 0.44674389])

In [74]:
M.max(axis=1)

array([0.90629332, 0.72231083, 0.51486002])

In [75]:
M.min()

0.1659242498140202

In [76]:
# Broadcasting 

a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [77]:
a + 5

array([5, 6, 7])

In [78]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [79]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [80]:
# Sort
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [81]:
x

array([2, 1, 4, 3, 5])

In [82]:
i = np.argsort(x) #index of the sorted elements
print(i)

[1 0 3 2 4]


In [83]:
np.argmax(x), np.argmin(x)

(4, 1)

In [84]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [85]:
# sort each column of X
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [86]:
# sort each row of X
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [87]:
# argmax and argmin

a = np.array([[1,2,4,7], [9,88,6,45], [9,76,3,4]])

a

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 9, 76,  3,  4]])

In [88]:
np.argmax(a)

5

In [89]:
np.argmax(a,axis=0)

array([1, 1, 1, 1])

In [90]:
np.argmax(a,axis=1)

array([3, 1, 1])

In [91]:
np.argmin(a)

0

In [92]:
np.argmin(a,axis=0)

array([0, 0, 2, 2])

In [93]:
np.argmin(a,axis=1)

array([0, 2, 2])

----------------------------------------